---
- name: Compliance Check
  hosts: localhost
  vars_files:
    - vars/matrix.yml
    - vars/policy_params.yml

  tasks:
    - name: Load test case
      set_fact:
        srcintf: "{{ vars[active_test].srcintf }}"
        dstintf: "{{ vars[active_test].dstintf }}"
        service: "{{ vars[active_test].service }}"

    - name: Validate rule
      template:
        src: "templates/fortigate_rule.j2"  # Fixed path (was missing 's' in templates)
        dest: "/tmp/rule_check.txt"

    - name: Show result
      debug:
        msg: |
          RULE CHECK:
          From: {{ srcintf }}
          To: {{ dstintf }}
          Service: {{ service }}
          STATUS: {% if lookup('file', '/tmp/rule_check.txt').strip() == 'ALLOWED' %}✅ ALLOWED{% else %}❌ NOT ALLOWED{% endif %}

    - name: Cleanup
      file:
        path: "/tmp/rule_check.txt"
        state: absent